#!bin/bash
#https://www.cnblogs.com/hester/p/10455215.html

#1.模拟延迟传输
#tc qdisc add dev eth0 root netem delay 100ms 将 eth0 网卡的传输设置为延迟100毫秒发送
#tc qdisc add dev eth0 root netem delay 100ms 10ms eth0 网卡的传输设置为延迟 100ms ± 10ms （90 ~ 110 ms 之间的任意值）发送
#tc qdisc add dev eth0 root netem delay 100ms 10ms 30%  将 eth0 网卡的传输设置为 100ms ，同时，大约有 30% 的包会延迟 ± 10ms 发送

#2.模拟网络丢包
#tc qdisc add dev eth0 root netem loss 1%  将 eth0 网卡的传输设置为随机丢掉 1% 的数据包
#tc qdisc add dev eth0 root netem loss 1% 30% 将 eth0 网卡的传输设置为随机丢掉 1% 的数据包，成功率为 30%

#3.模拟包重复
#tc qdisc add dev eth0 root netem duplicate 1%  将 eth0 网卡的传输设置为随机产生 1% 的重复数据包

#4.模拟数据包损坏
#tc qdisc add dev eth0 root netem corrupt 0.2%  将 eth0 网卡的传输设置为随机产生 0.2% 的损坏的数据包 。 (内核版本需在2.6.16以上）

#5.模拟数据包乱序
#tc qdisc change dev eth0 root netem delay 10ms reorder 25% 50% 将 eth0 网卡的传输设置为:有 25% 的数据包（50%相关）会被立即发送，其他的延迟 10 秒。
#新版本中，如下命令也会在一定程度上打乱发包的次序 tc qdisc add dev eth0 root netem delay 100ms 10ms





